"""
This is a setup.py script generated by py2applet

Usage:
    python py2app_setup.py py2app
"""
import sys
from setuptools import setup

mainscript = 'f-engrave.py'
version = "1.68"
url = "https://github.com/agarthetiger/f-engrave"

extra_options = dict(
    setup_requires=['py2app'],
    options=dict(py2app = {
        'argv_emulation': False,
        'argv_inject': ['--fontdir', '/Library/Fonts', '--defdir', '~/Documents'],
        'iconfile': 'fengrave.icns',
        'resources': ['TTF2CXF_STREAM/ttf2cxf_stream'],
    }),
)

setup(
    #name="F-Engrave",
    app=[mainscript],
    version=version,
    url=url,
    **extra_options
)
